# Generated by Django 2.0.1 on 2018-01-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('event', models.IntegerField(primary_key=True, serialize=False)),
                ('occupant', models.IntegerField(null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatsapp.Layout')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together={('rank', 'row', 'seat')},
        ),
        migrations.AddField(
            model_name='flag',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatsapp.Layout'),
        ),
        migrations.AlterUniqueTogether(
            name='seating',
            unique_together={('seat', 'event', 'occupant')},
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('seat', 'flag')},
        ),
    ]
